version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    restart: always
